### ISSUE TITLE
Potential collaboration 

### ISSUE THREAD

**Issue by huard** [ClimateImpactLab/downscale#56]
Hi, we ([Ouranos](https://github.com/Ouranosinc/)) have a similar interest in building a library of empirical downscaling methods built on xarray. Recently I've added the quantile method to `groupby` objects in xarray, which simplifies the implementation of quantile-based correction methods (see https://github.com/Ouranosinc/xclim/pull/246 for a first rough draft). 

Let us know if this is something you are still considering, as we'd be glad to join efforts.

**Comment by delgadom** [comment]
Hi @huard - thanks for reaching out! We will be beginning work on this in earnest in a couple months and would definitely be interested in swapping & collaborating on tools. I'd also point you to https://github.com/jhamman/xsd which is I think heading in the same direction and is probably where we'd start.

Pinging a couple relevant parties on our end: @kemccusker @dgergel

**Comment by huard** [comment]
@delgadom Excellent ! I suggest we then move this conversation to xsd and maybe setup a telco with @jhamman to share our vision for this.
